# Generated by Django 2.2.16 on 2022-06-14 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', regex='^[\\w.@+-]+\\z')]),
        ),
    ]
