# Generated by Django 2.2.16 on 2022-06-01 12:01

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('reviews', '0003_auto_20220601_0024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
    ]
